# Site settings
title: DUA(L)UA
description: "Open source hub for Dual Universe related LUA."
url: "https://dualua.github.io/"

# Secondary Parameters
baseurl: "/"
headercolor: "#000000"
# Tertiary Parameters
#g-analytics:

# Build settings
plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg.jpg"
